fix: upload crashes on linux
getsentry/crashpad pull request #75
Opened 2022-12-09 08:35 UTC by BogdanLivadariu

as per description and comments on:  https://github.com/getsentry/sentry-native/issues/773

2022-12-09 08:41 UTC, BogdanLivadariu commented
tested changes with a custom build of sentry-native on the latest release(0.5.3) and crashes do get uploaded now on linux hosts

2022-12-09 08:51 UTC, Swatinem reviewed
I believe you have to find / declare libcurl as a dependency to crashpad now.
For `sentry-native` that just works as it depends on curl itself already.

2022-12-12 08:46 UTC, Swatinem commented
You also have to add the found curl package to the dependencies :-)

@supervacuus can help you with that

2022-12-13 11:48 UTC, supervacuus commented
Hi @BogdanLivadariu, thanks for starting this off.

2023-01-05 11:02 UTC, supervacuus commented
@BogdanLivadariu, are you planning to finish this PR?

2023-01-05 13:02 UTC, BogdanLivadariu commented
Hi @supervacuus 
I would ... but my experience with cmake is not at its best, if you could guide me on where to 
`add the found curl package to the dependencies` that would be great

2023-01-05 16:09 UTC, supervacuus commented
@BogdanLivadariu, you can start by applying all pending change suggestions, which do most of the work.

2023-01-05 16:10 UTC, supervacuus requested changes

2023-01-05 16:10 UTC, supervacuus commented on util/CMakeLists.txt
> +    find_package(CURL REQUIRED)
I think here it would be best to mimic the configuration of [upstream](https://chromium.googlesource.com/crashpad/crashpad/+/refs/heads/main/util/net/tls.gni#18):

```suggestion
    if (LINUX)
        find_package(CURL REQUIRED)
        target_include_directories(crashpad_util PRIVATE ${CURL_INCLUDE_DIRS})
        target_link_libraries(crashpad_util PRIVATE ${CURL_LIBRARIES})
        SET(HTTP_TRANSPORT_IMPL net/http_transport_libcurl.cc)
    else()
        SET(HTTP_TRANSPORT_IMPL net/http_transport_socket.cc)
    endif()
```

2023-01-05 16:10 UTC, supervacuus commented on util/CMakeLists.txt
> +        net/http_transport_libcurl.cc
Then we can replace the hard-coded transport translation unit with a variable reference:
```suggestion
        ${HTTP_TRANSPORT_IMPL}
```

2023-01-12 14:18 UTC, BogdanLivadariu commented
hi @supervacuus does this looks good to go ?
should I squash the commits ?

thanks for the suggestions

2023-01-13 09:36 UTC, supervacuus commented
LGTM @BogdanLivadariu; no need to squash, we will do this. Thx!

2023-01-16 12:06 UTC, supervacuus commented on util/CMakeLists.txt
> +        target_link_libraries(crashpad_util PRIVATE ${CURL_LIBRARIES})
```suggestion
        find_package(CURL REQUIRED)
        if(TARGET CURL::libcurl) # CMake >= 3.12
            target_link_libraries(crashpad_util PRIVATE CURL::libcurl)
        else() # CMake < 3.12
            target_include_directories(crashpad_util PRIVATE ${CURL_INCLUDE_DIR})
            string(REPLACE ";" "$<SEMICOLON>" GENEX_CURL_LIBRARIES "${CURL_LIBRARIES}")
            target_link_libraries(crashpad_util PRIVATE $<BUILD_INTERFACE:${GENEX_CURL_LIBRARIES}>)
        endif()
```

2023-01-17 11:29 UTC, supervacuus commented
@Swatinem, can I ask you to merge this?

2023-01-17 13:52 UTC, merged

2023-01-25 03:11 UTC, bsergean commented
Could we do the if(NOT CURL_FOUND) around the find_package trick ?

https://github.com/bsergean/crashpad/pull/1/files

2023-01-25 06:56 UTC, supervacuus commented
> Could we do the if(NOT CURL_FOUND) around the find_package trick ?

There is no "trick" involved :-) This is how `FindCURL` is supposed to work in layered CMake projects. A few other changes are also needed before we update the submodule in the Native SDK, which I will finish today.

2023-01-25 15:23 UTC, bsergean commented
Ok great.

For context we are using the breakpad backend now, but it would be nice to be able to use the crashpad one, because it feels more robust in case of an early crash. We are calling our binary twice from a shell script (a second time in ‘reporting mode’ where we exit right after we’ve uploaded a potential crash). In environments like Kubernetes, it can be hard to have access to the same sentry database path the 'second time'

> On Jan 24, 2023, at 10:56 PM, Mischan Toosarani-Hausberger ***@***.***> wrote:
> 
> 
> Could we do the if(NOT CURL_FOUND) around the find_package trick ?
> 
> There is no "trick" involved :-) This is how FindCURL is supposed to work in layered CMake projects. A few other changes are also needed before we update the submodule in the Native SDK, which I will finish today.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/getsentry/crashpad/pull/75#issuecomment-1403173824>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AC2O6UIHXZN4O2N5QQ2WJBTWUDFCFANCNFSM6AAAAAASZCQGTQ>.
> You are receiving this because you commented.
>